const profileActionTypes = {
    GET_PROFILE: 'GET_PROFILE',
    PROFILE_ERROR: 'PROFILE_ERROR',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    GET_PROFILES: 'GET_PROFILES',
    GET_GITHUBREPOS: 'GET_GITHUBREPOS'
}
export default profileActionTypes;