name: Node.js CI/CD

on:
  push:
    branches: ["master", "pipelines"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR Public
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Create ECR Repository if Not Exists
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECR_REPOSITORY: devnetwork-repository
        run: |
          echo "Checking if ECR repository exists..."
          if ! aws ecr describe-repositories --region $AWS_REGION --repository-names $ECR_REPOSITORY > /dev/null 2>&1; then
            echo "ECR repository does not exist. Creating..."
            aws ecr create-repository --repository-name $ECR_REPOSITORY --region $AWS_REGION
          else
            echo "ECR repository already exists."
          fi

      - name: Build and Push Docker Image
        id: build-image
        env:
          ECR_REPOSITORY: devnetwork-repository
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Get the full registry URL output by the login action
          REGISTRY_URL="${{ steps.login-ecr.outputs.registry }}"
          # Extract the dynamic registry ID (assuming the format "public.ecr.aws/<registry_id>")
          REGISTRY_ID=$(echo "$REGISTRY_URL" | cut -d'/' -f2)
          echo "Dynamic Registry ID: $REGISTRY_ID"
          
          # Construct the full image URI using the registry URL directly
          IMAGE_URI="$REGISTRY_URL/$ECR_REPOSITORY:$IMAGE_TAG"
          
          echo "Building Docker image with tag: $IMAGE_URI"
          docker build -t $IMAGE_URI .
          
          echo "Pushing Docker image..."
          docker push $IMAGE_URI
          
          echo "::set-output name=image::$IMAGE_URI"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        working-directory: ./ecs-terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./ecs-terraform
        run: terraform apply -auto-approve \
              -var="container_image=${{ steps.build-image.outputs.image }}" \
              -var="env_config=${{ secrets.MY_CONFIG_JSON }}"
