name: Node.js CI

on:
  push:
    branches: [ "master", "pipelines" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: |
        cd client  
        npm install 
        export NODE_OPTIONS=--openssl-legacy-provider
        CI=false npm run build
        ls -a 
    
  build-node:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: |
        ls -a 
        ls -a client
